### ISSUE TITLE
Suggestions for function winsor

### ISSUE THREAD

**Issue by leima0521** [ganong-noel/lab_code#1]
- [x] Upload function `winsor.R` to the repo.

- [x] Add comment regarding the issue when using `winsor` and `dplyr::mutate` together on grouped data.

- [x] Revise `min(x)` and `max(x)` so that the text message shows properly for `NA` values.

**Comment by leima0521** [comment]
@ganong123 

I've uploaded the modified [`winsor.R`](https://github.com/ganong-noel/lab_code/blob/9062f69c4905d614845d51bf88f85393782dd6d6/winsor.R) to branch `issue1_winsor`. 

- Do I need to do a pull request?
- Do I need to add anything to `README.md`?

**Comment by ganong123** [comment]
@leima0521 
1. yes please.
1. good idea. while you are at it, can you update `README.md` with a brief list of the functions included in `prelim.R`

**Comment by leima0521** [comment]
@ganong123 

1. Done.
2. `prelim.R` only has the functions to make plots: fte_theme and coef_label. Do you want me to make a list of these two functions? It does not seem to be so necessary to me. Or you also want me to add function winsor to `prelim.R`?

**Comment by ganong123** [comment]
lets add winsor and yes list three functions. I expect in the future we will add more functions.

**Comment by leima0521** [comment]
@ganong123 

I merged the issue branch to master branch. 

1. Function `winsor` is added to [`prelim.R`](https://github.com/ganong-noel/lab_code/blob/6761d5ce7db0a7d6ee89dc40c606b64e2f3f50b4/prelim.R).
2. I updated [`README.md`](https://github.com/ganong-noel/lab_code/blob/6761d5ce7db0a7d6ee89dc40c606b64e2f3f50b4/README.md) to list functions in `prelim.R`.
